name: Slack Bot Test
on:
  push:
    branches: [slack-bot-test]

jobs:
  validation:
    name: Slack Bot Test
    runs-on: ubuntu-20.04

    steps:
      - name: Slack Alert Notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "Suggest Chain Alert",
              "attachments": [
                {
                  "color": "FB486C",
                  "fields": [
                    {
                      "title": "Error Message",
                      "short": false,
                      "value": "test"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
